apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: hatest01
  namespace: metallb-system
spec:
  ipAddressPools:
    - vip-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: lima-metallb2
  - matchLabels:
      kubernetes.io/hostname: lima-metallb3